spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123123
    url: jdbc:mysql://127.0.0.1/springcloud?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
server:
  port: 8081
env:
  message: 111
