spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123123
    url: jdbc:mysql://127.0.0.1/springcloud?characterEncoding=utf-8&useSSL=false
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672
  jpa:
    show-sql: true
